using PinqOps.Proxy;
using Xunit;

namespace PinqOps.Tests.Proxy;

public class CaddyfileGeneratorTests
{
    private static DomainEntry Entry(string domain, string container, int port, bool enabled = true) =>
        new() { Domain = domain, TargetContainer = container, TargetPort = port, Enabled = enabled };

    [Fact]
    public void EmptyConfig_HasOnlyTheHeader()
    {
        var caddyfile = CaddyfileGenerator.Generate(new DomainConfig());

        Assert.Equal("# Generated by pinqops-ui — do not edit; changes are overwritten.\n", caddyfile);
        Assert.True(CaddyfileGenerator.IsEffectivelyEmpty(caddyfile));
    }

    [Fact]
    public void ASiteBlockIsNotEffectivelyEmpty()
    {
        var caddyfile = CaddyfileGenerator.Generate(new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [Entry("app.example.com", "myrepo-app-1", 3000)],
        });

        Assert.False(CaddyfileGenerator.IsEffectivelyEmpty(caddyfile));
    }

    [Fact]
    public void ProxyDeferredDomain_IsOmittedFromCaddyfile()
    {
        var deferred = Entry("pending.example.com", "myrepo-app-1", 3000);
        deferred.ProxyDeferred = true;
        var live = Entry("live.example.com", "myrepo-app-1", 3000);
        var render = CaddyfileGenerator.GenerateWithDiagnostics(new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [deferred, live],
        });

        Assert.DoesNotContain("pending.example.com {", render.Caddyfile, StringComparison.Ordinal);
        Assert.Contains("live.example.com {\n", render.Caddyfile, StringComparison.Ordinal);
        Assert.Contains(render.Skipped, skip => skip.What == "pending.example.com");
    }

    [Fact]
    public void SingleDomain_RendersASiteBlock()
    {
        var config = new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [Entry("app.example.com", "myrepo-app-1", 3000)],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.Contains("email ops@example.com", caddyfile);
        Assert.Contains("app.example.com {\n", caddyfile);
        Assert.Contains("    reverse_proxy myrepo-app-1:3000\n}\n", caddyfile);
        Assert.DoesNotContain("acme_ca", caddyfile);
        Assert.DoesNotContain("tls /etc/caddy/log/certs/", caddyfile);
    }

    [Fact]
    public void ACustomTlsDomain_PointsCaddyAtTheMountedCertFiles()
    {
        var entry = Entry("app.example.com", "myrepo-app-1", 3000);
        entry.TlsMode = DomainTlsModes.Custom;
        entry.Security = new SecurityHeaders { Enabled = false };

        var caddyfile = CaddyfileGenerator.Generate(new DomainConfig { Domains = [entry] });

        Assert.Contains(
            "tls /etc/caddy/log/certs/app.example.com/fullchain.pem /etc/caddy/log/certs/app.example.com/privkey.pem",
            caddyfile);
        Assert.Contains("reverse_proxy myrepo-app-1:3000", caddyfile);
    }

    /// <summary>A domain with headers turned off renders exactly what it always did.</summary>
    [Fact]
    public void WithHeadersOff_TheSiteBlockIsJustTheUpstream()
    {
        var entry = Entry("app.example.com", "myrepo-app-1", 3000);
        entry.Security = new SecurityHeaders { Enabled = false };

        Assert.Contains(
            "app.example.com {\n    reverse_proxy myrepo-app-1:3000\n}\n",
            CaddyfileGenerator.Generate(new DomainConfig { Domains = [entry] }));
    }

    [Fact]
    public void StagingCa_EmitsTheStagingDirective()
    {
        var config = new DomainConfig { UseStagingCa = true, Domains = [Entry("a.example.com", "c", 80)] };

        Assert.Contains("acme_ca https://acme-staging-v02.api.letsencrypt.org/directory", CaddyfileGenerator.Generate(config));
    }

    [Fact]
    public void DisabledOrUnresolvedEntries_AreSkipped()
    {
        var config = new DomainConfig
        {
            Domains =
            [
                Entry("off.example.com", "c1", 80, enabled: false),
                Entry("noport.example.com", "c2", 0),
                Entry("live.example.com", "c3", 8080),
            ],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.DoesNotContain("off.example.com", caddyfile);
        Assert.DoesNotContain("noport.example.com", caddyfile);
        Assert.Contains("live.example.com {", caddyfile);
    }

    [Fact]
    public void NoEmail_OmitsTheGlobalBlock()
    {
        var config = new DomainConfig { Domains = [Entry("a.example.com", "c", 80)] };

        Assert.DoesNotContain("{\n    email", CaddyfileGenerator.Generate(config));
    }

    // ---- port blocks --------------------------------------------------------

    private static PortEntry Port(int hostPort, string container, int targetPort, bool enabled = true) =>
        new() { HostPort = hostPort, TargetContainer = container, TargetPort = targetPort, Enabled = enabled };

    /// <summary>
    /// A bare ":port" address, which Caddy deliberately serves over plain HTTP with
    /// no certificate — an app that used to publish 8080 itself has to keep
    /// answering there exactly as it did.
    /// </summary>
    [Fact]
    public void APortEntry_RendersABarePortBlock()
    {
        var config = new DomainConfig { Ports = [Port(8080, "myrepo-app-1", 3000)] };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.Contains(":8080 {\n    reverse_proxy myrepo-app-1:3000\n}\n", caddyfile);
    }

    [Fact]
    public void DomainsAndPortsCoexist()
    {
        var config = new DomainConfig
        {
            Domains = [Entry("app.example.com", "myrepo-app-1", 3000)],
            Ports = [Port(8080, "myrepo-app-1", 3000)],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.Contains("app.example.com {", caddyfile);
        Assert.Contains(":8080 {", caddyfile);
    }

    /// <summary>80 and 443 are the proxy's own listeners; a site block on one would
    /// collide with the automatic HTTP and HTTPS servers.</summary>
    [Theory]
    [InlineData(80)]
    [InlineData(443)]
    public void APortEntryClaimingTheProxysOwnPortsIsSkipped(int reserved)
    {
        var render = CaddyfileGenerator.GenerateWithDiagnostics(
            new DomainConfig { Ports = [Port(reserved, "c", 3000)] });

        Assert.DoesNotContain($":{reserved} {{", render.Caddyfile);
        Assert.Single(render.Skipped);
    }

    /// <summary>
    /// Two site blocks with the same address make Caddy refuse the whole file, which
    /// would take every other route down with it — so the duplicate is dropped and
    /// reported rather than emitted.
    /// </summary>
    [Fact]
    public void ADuplicatePortIsEmittedOnceAndReported()
    {
        var config = new DomainConfig
        {
            Ports = [Port(8080, "first-app-1", 3000), Port(8080, "second-app-1", 3000)],
        };

        var render = CaddyfileGenerator.GenerateWithDiagnostics(config);

        Assert.Contains("first-app-1:3000", render.Caddyfile);
        Assert.DoesNotContain("second-app-1", render.Caddyfile);
        Assert.Contains(render.Skipped, skip => skip.Reason.Contains("already publishes", StringComparison.Ordinal));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(70000)]
    public void AnOutOfRangePortIsSkipped(int port)
    {
        var render = CaddyfileGenerator.GenerateWithDiagnostics(
            new DomainConfig { Ports = [Port(port, "c", 3000)] });

        Assert.Single(render.Skipped);
    }

    // ---- diagnostics --------------------------------------------------------

    /// <summary>
    /// Skipping used to be silent. A skipped entry is a route the dashboard lists as
    /// enabled and Caddy never serves, so what was left out — and why — has to come
    /// back with the file.
    /// </summary>
    [Fact]
    public void WhatIsSkippedIsReportedWithAReason()
    {
        var config = new DomainConfig
        {
            Domains =
            [
                Entry("live.example.com", "good-app-1", 3000),
                Entry("bad.example.com", "not a container name", 3000),
                Entry("noport.example.com", "c", 0),
            ],
        };

        var render = CaddyfileGenerator.GenerateWithDiagnostics(config);

        Assert.Contains("live.example.com {", render.Caddyfile);
        Assert.Equal(2, render.Skipped.Count);
        Assert.All(render.Skipped, skip => Assert.False(string.IsNullOrWhiteSpace(skip.Reason)));
        Assert.Contains(render.Skipped, skip => skip.What == "bad.example.com");
        Assert.Contains(render.Skipped, skip => skip.What == "noport.example.com");
    }

    /// <summary>A disabled entry is a choice, not a failure, so it is not reported.</summary>
    [Fact]
    public void ADisabledEntryIsNotReportedAsSkipped()
    {
        var render = CaddyfileGenerator.GenerateWithDiagnostics(
            new DomainConfig { Domains = [Entry("off.example.com", "c", 80, enabled: false)] });

        Assert.Empty(render.Skipped);
    }

    [Fact]
    public void GenerateReturnsExactlyWhatTheDiagnosticFormRenders()
    {
        var config = new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [Entry("app.example.com", "myrepo-app-1", 3000)],
            Ports = [Port(8080, "myrepo-app-1", 3000)],
        };

        Assert.Equal(CaddyfileGenerator.GenerateWithDiagnostics(config).Caddyfile, CaddyfileGenerator.Generate(config));
    }

    // ---- grace period -------------------------------------------------------

    [Fact]
    public void AGracePeriodIsEmittedIntoTheGlobalBlock()
    {
        var config = new DomainConfig { GracePeriodSeconds = 15, Domains = [Entry("a.example.com", "c", 80)] };

        Assert.Contains("grace_period 15s", CaddyfileGenerator.Generate(config));
    }

    [Fact]
    public void NoGracePeriodEmitsNoDirective()
    {
        Assert.DoesNotContain("grace_period", CaddyfileGenerator.Generate(new DomainConfig()));
    }

    /// <summary>
    /// Clamped rather than skipped: dropping a safety setting because someone typed
    /// too many zeroes would quietly go back to cutting live requests on every
    /// proxy restart.
    /// </summary>
    [Fact]
    public void AnAbsurdGracePeriodIsClampedNotDropped()
    {
        var config = new DomainConfig { GracePeriodSeconds = 999_999 };

        Assert.Contains("grace_period 600s", CaddyfileGenerator.Generate(config));
    }

    // ---- access log ---------------------------------------------------------

    /// <summary>
    /// The two ends of the same file have to meet. The proxy mounts the Caddyfile as
    /// a single read-only file, not its directory, so the path Caddy is told to write
    /// to cannot sit beside it at <c>/etc/caddy</c> — a log written there never
    /// leaves the container's writable layer, and the traffic summary reads the host
    /// file, finds nothing, and reports zero requests after any amount of traffic. It
    /// belongs under the directory the proxy bind-mounts, which is the one the
    /// dashboard reads back through <see cref="ProxyPaths.AccessLogFile"/>.
    /// </summary>
    [Fact]
    public void TheAccessLogPathTheProxyWritesToIsInsideTheMountedDirectory()
    {
        Assert.Equal($"{ProxyPaths.LogDirectory}/access.log", ProxyPaths.AccessLogPath);
        Assert.NotEqual("/etc/caddy", ProxyPaths.LogDirectory);
        Assert.Equal(
            Path.GetFileName(ProxyPaths.AccessLogPath),
            Path.GetFileName(ProxyPaths.AccessLogFile(ProxyPaths.DefaultDirectory)));
    }

    /// <summary>
    /// The only domain in this config, with headers off so the site block is the
    /// upstream and nothing else — which makes the log block's position and
    /// indentation inside it something a test can state exactly.
    /// </summary>
    private static DomainConfig WithAccessLog(bool enabled)
    {
        var entry = Entry("app.example.com", "myrepo-app-1", 3000);
        entry.Security = new SecurityHeaders { Enabled = false };
        return new DomainConfig { AccessLog = enabled, Domains = [entry] };
    }

    /// <summary>
    /// Turning the access log on has to reach the file Caddy executes. The block was
    /// assembled and then dropped on the way into the site block, so Caddy was never
    /// told to write anything: the Traffic page reported zero requests, zero errors,
    /// no routes and no p95 after any amount of real traffic — indistinguishable from
    /// nobody having visited, with nothing logged anywhere to say otherwise.
    /// </summary>
    [Fact]
    public void WithTheAccessLogOn_TheSiteBlockTellsCaddyWhereToWrite()
    {
        var caddyfile = CaddyfileGenerator.Generate(WithAccessLog(enabled: true));

        Assert.Contains(
            $$"""
            app.example.com {
                log {
                    output file {{ProxyPaths.AccessLogPath}} {
                        roll_size 32MiB
                        roll_keep 3
                    }
                    format json
                }
                reverse_proxy myrepo-app-1:3000
            }

            """.ReplaceLineEndings("\n"),
            caddyfile);
    }

    /// <summary>
    /// The log is rolled by Caddy itself. Without the roll settings reaching the
    /// file, the one thing nothing prunes grows on the proxy until the server's disk
    /// is full and every app on it stops.
    /// </summary>
    [Fact]
    public void WithTheAccessLogOn_TheLogIsRolledRatherThanLeftToGrow()
    {
        var caddyfile = CaddyfileGenerator.Generate(WithAccessLog(enabled: true));

        Assert.Contains("roll_size 32MiB", caddyfile);
        Assert.Contains("roll_keep 3", caddyfile);
        Assert.Contains("format json", caddyfile);
    }

    /// <summary>
    /// Every enabled domain writes, not just the first one — a route whose block is
    /// missing the directive is a route the Traffic page shows no requests for while
    /// its neighbours look busy.
    /// </summary>
    [Fact]
    public void WithTheAccessLogOn_EveryDomainWritesToIt()
    {
        var config = new DomainConfig
        {
            AccessLog = true,
            Domains = [Entry("first.example.com", "first-app-1", 3000), Entry("second.example.com", "second-app-1", 3000)],
        };

        var caddyfile = CaddyfileGenerator.Generate(config);

        Assert.Equal(2, CountOccurrences(caddyfile, $"output file {ProxyPaths.AccessLogPath}"));
    }

    /// <summary>
    /// Off is every existing install, and it has to render the file it rendered
    /// before: an operator who never asked for a log must not have one appear, be
    /// charged the disk for it, or find the proxy reloaded over a change nobody made.
    /// </summary>
    [Fact]
    public void WithTheAccessLogOff_NoLogBlockIsEmitted()
    {
        var caddyfile = CaddyfileGenerator.Generate(WithAccessLog(enabled: false));

        Assert.DoesNotContain("log {", caddyfile);
        Assert.DoesNotContain("output file", caddyfile);
        Assert.Contains("app.example.com {\n    reverse_proxy myrepo-app-1:3000\n}\n", caddyfile);
    }

    private static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var index = haystack.IndexOf(needle, StringComparison.Ordinal);
        while (index >= 0)
        {
            count++;
            index = haystack.IndexOf(needle, index + needle.Length, StringComparison.Ordinal);
        }

        return count;
    }

    // ---- injection ----------------------------------------------------------

    /// <summary>
    /// domains.json is written by two processes and loaded without validation, so
    /// this generator is the last boundary before Caddy executes the file.
    /// </summary>
    [Theory]
    [InlineData("bad name")]
    [InlineData("c\n}\nevil.example.com {")]
    [InlineData("-leading-dash")]
    [InlineData("c:1234 other")]
    public void AContainerNameThatCouldBreakOutIsSkipped(string container)
    {
        var render = CaddyfileGenerator.GenerateWithDiagnostics(
            new DomainConfig { Domains = [Entry("a.example.com", container, 3000)] });

        Assert.DoesNotContain("a.example.com {", render.Caddyfile);
        Assert.Single(render.Skipped);
    }

    [Fact]
    public void AnAcmeEmailThatCouldBreakOutIsSkipped()
    {
        var render = CaddyfileGenerator.GenerateWithDiagnostics(
            new DomainConfig { AcmeEmail = "ops@example.com}\nevil {" });

        Assert.DoesNotContain("evil", render.Caddyfile);
        Assert.Single(render.Skipped);
    }
}

public class DomainNameTests
{
    [Theory]
    [InlineData("App.Example.COM", "app.example.com")]
    [InlineData("api.example.com.", "api.example.com")]
    public void Normalize_LowercasesAndTrims(string input, string expected)
    {
        Assert.Equal(expected, DomainName.Normalize(input));
    }

    [Theory]
    [InlineData("")]
    [InlineData("*.example.com")]
    [InlineData("not a domain")]
    [InlineData("http://example.com")]
    public void Normalize_RejectsInvalid(string input)
    {
        Assert.Throws<ArgumentException>(() => DomainName.Normalize(input));
    }

    [Theory]
    [InlineData("App.Example.COM", "app.example.com")]
    [InlineData("  api.example.com  ", "api.example.com")]
    // The absolute form of an FQDN. Normalize strips the root label, so a lookup
    // that does not is comparing two different strings for the same domain.
    [InlineData("api.example.com.", "api.example.com")]
    public void NormalizeForLookup_FoldsExactlyAsNormalizeStores(string input, string expected)
    {
        Assert.Equal(expected, DomainName.NormalizeForLookup(input));
        Assert.Equal(DomainName.Normalize(input), DomainName.NormalizeForLookup(input));
    }

    [Theory]
    [InlineData("*.example.com")]
    [InlineData("not a domain")]
    public void NormalizeForLookup_DoesNotValidate(string input)
    {
        // A route already on file has to stay addressable — and therefore
        // removable — even when it would no longer pass Normalize.
        Assert.Throws<ArgumentException>(() => DomainName.Normalize(input));
        Assert.Equal(input.Trim().ToLowerInvariant(), DomainName.NormalizeForLookup(input));
    }
}

public class DomainConfigStoreTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("pinqops-domains-").FullName;

    public void Dispose() => Directory.Delete(_dir, recursive: true);

    [Fact]
    public void SaveThenLoad_RoundTrips()
    {
        var store = new DomainConfigStore(_dir);
        var config = new DomainConfig
        {
            AcmeEmail = "ops@example.com",
            Domains = [new DomainEntry { Domain = "a.example.com", Target = "acme-shop", TargetContainer = "acme-shop-app-1", TargetPort = 3000 }],
        };

        store.Save(config);
        var loaded = new DomainConfigStore(_dir).Load();

        Assert.Equal("ops@example.com", loaded.AcmeEmail);
        var entry = Assert.Single(loaded.Domains);
        Assert.Equal("a.example.com", entry.Domain);
        Assert.Equal("acme-shop-app-1", entry.TargetContainer);
    }

    [Fact]
    public void Load_CorruptFile_ReturnsEmpty()
    {
        File.WriteAllText(ProxyPaths.DomainsFile(_dir), "{ not json");

        Assert.Empty(new DomainConfigStore(_dir).Load().Domains);
    }
}
