namespace PinqOps;

/// <summary>
/// The application compose project pinqops generates — shared by the dashboard
/// (the fixed prod project) and the CLI (per-PR preview projects), so both emit
/// exactly the same shape. The project name is explicit so a preview can use
/// <c>&lt;repo&gt;-pr-&lt;n&gt;</c> instead of the repository name.
/// </summary>
public static class ComposeTemplate
{
    /// <summary>
    /// The network every project used before apps got their own. Still the default,
    /// because a project already on it is reaching a database through it.
    /// </summary>
    public const string SharedNetwork = "pinqops-apps";

    /// <summary>
    /// The compose project for an app.
    ///
    /// <para><paramref name="network"/> is the external network the app joins,
    /// defaulting to the shared one. A newly published app is given its own, so it
    /// cannot reach another app's database until somebody connects the two; the
    /// proxy is connected to it, which is what keeps the domain and the published
    /// port working.</para>
    /// </summary>
    public static string Yaml(
        string owner,
        string repo,
        string projectName,
        int hostPort,
        int containerPort,
        string? network = null)
    {
        var joined = string.IsNullOrWhiteSpace(network) ? SharedNetwork : network;
        var note = joined == SharedNetwork
            ? "# pinqops-apps is the shared network the catalog apps live on — it\n"
                + "            # lets this app reach them (Redis, PostgreSQL, …) by container DNS."
            : "# This app's own network. The proxy is on it, so domains and the\n"
                + "            # published port work; nothing else is until you connect it,\n"
                + "            # which is what keeps one app out of another's database.";

        return $$"""
        # Generated by pinqops-ui — the application compose project.
        # `pinqops deploy` runs: docker compose pull && docker compose up -d
        # Quoted: an all-digit project name (e.g. "2048") would otherwise be
        # read as a YAML integer and compose rejects the file outright.
        name: "{{projectName}}"

        services:
          app:
            # Both variables are pinned in this directory's .env by `pinqops
            # deploy` (PINQOPS_IMAGE from --image, PINQOPS_TAG from --tag), so the
            # image always follows the repository — even after a rename — and the
            # exact version is recorded and can be rolled back. The defaults below
            # are used only before the first deploy (or a plain `docker compose up`).
            image: ${PINQOPS_IMAGE:-ghcr.io/{{owner.ToLowerInvariant()}}/{{repo.ToLowerInvariant()}}}:${PINQOPS_TAG:-latest}
            restart: unless-stopped
            # <host>:<container>. Change the host port from the dashboard's .env
            # editor (PINQOPS_HOST_PORT) and press Apply — no need to edit YAML.
            # PINQOPS_CONTAINER_PORT is the port your image listens on; it was
            # read from your Dockerfile's EXPOSE.
            ports:
              - "${PINQOPS_HOST_PORT:-{{hostPort}}}:${PINQOPS_CONTAINER_PORT:-{{containerPort}}}"
            {{note}}
            # PINQOPS_ALIAS is the name the proxy forwards to. It is pinned by
            # deploy, and it is per-project on purpose: two projects sharing an
            # alias share traffic.
            networks:
              default:
              {{joined}}:
                aliases:
                  - "${PINQOPS_ALIAS:-{{projectName}}}"
            # Add whatever else YOUR application needs here (volumes, env):

        networks:
          {{joined}}:
            external: true
        """;
    }
}
