namespace PinqOps.Mail;

/// <summary>
/// One record to create at the DNS provider.
/// </summary>
/// <param name="Purpose">Why it exists, in one line, for the operator reading the list.</param>
/// <param name="Placeholder">
/// True when the value cannot be computed here and has to be fetched from
/// somewhere else — a DKIM key, a provider's SPF include. The page shows those
/// differently, because a placeholder pasted into a zone verbatim is worse than
/// no record at all.
/// </param>
public sealed record MailDnsRecord(
    string Type,
    string Name,
    string Value,
    string Purpose,
    bool Placeholder = false);

/// <summary>
/// The DNS records mail from a domain needs, worked out from what the operator
/// has already told pinqops.
///
/// <para><b>Why this exists at all.</b> A message that leaves a server with no SPF
/// record and no DKIM signature does not bounce — it is accepted, filed as spam,
/// and never mentioned again. The three records below are what makes the
/// difference, they are tedious to get exactly right, and getting one subtly wrong
/// (a missing <c>~all</c>, a DMARC policy set to reject before anything was
/// verified) is worse than not having it.</para>
///
/// <para><b>What it cannot do.</b> A DKIM public key is generated by whatever signs
/// the mail, so it is offered as a shape with the command that produces it rather
/// than as a value. Reverse DNS lives at the hosting provider, not in this
/// zone.</para>
/// </summary>
public static class MailDnsRecords
{
    /// <summary>The selector docker-mailserver uses unless it is told otherwise.</summary>
    public const string DefaultDkimSelector = "mail";

    /// <summary>What goes in the DKIM record until the real key is pasted in.</summary>
    public const string DkimKeyPlaceholder = "<the p= value from the generated key>";

    /// <summary>
    /// The records for <paramref name="domain"/>.
    /// </summary>
    /// <param name="mailHost">
    /// The host that sends or receives the mail — the MX target. Empty leaves the
    /// MX record out, which is right when the mail only ever goes out through a
    /// provider.
    /// </param>
    /// <param name="relayInclude">
    /// A provider's SPF include (<c>sendgrid.net</c>, <c>spf.mailgun.org</c>). When
    /// present, SPF authorises them; when absent, it authorises this domain's own
    /// MX.
    /// </param>
    /// <param name="reportTo">Where DMARC reports go. Empty leaves <c>rua</c> out.</param>
    public static IReadOnlyList<MailDnsRecord> For(
        string domain,
        string? mailHost = null,
        string? relayInclude = null,
        string? dkimSelector = null,
        string? reportTo = null)
    {
        var zone = NormalizeDomain(domain);
        var records = new List<MailDnsRecord>();

        var host = (mailHost ?? string.Empty).Trim().TrimEnd('.');
        if (host.Length > 0)
        {
            records.Add(new MailDnsRecord(
                "MX",
                zone,
                $"10 {host}.",
                "Where mail for this domain is delivered."));
        }

        records.Add(new MailDnsRecord(
            "TXT",
            zone,
            Spf(relayInclude, host),
            "Says which servers may send as this domain. Everything else is marked as a forgery."));

        var selector = (dkimSelector ?? string.Empty).Trim() is { Length: > 0 } chosen
            ? chosen
            : DefaultDkimSelector;

        records.Add(new MailDnsRecord(
            "TXT",
            $"{selector}._domainkey.{zone}",
            $"v=DKIM1; k=rsa; p={DkimKeyPlaceholder}",
            "The public half of the key the mail is signed with. Generate it on the mail server first — "
            + "docker-mailserver writes it with 'setup config dkim'.",
            Placeholder: true));

        var report = (reportTo ?? string.Empty).Trim();
        var dmarc = "v=DMARC1; p=none; adkim=r; aspf=r";
        if (EmailAddress.IsValid(report))
        {
            dmarc += $"; rua=mailto:{report}";
        }

        records.Add(new MailDnsRecord(
            "TXT",
            $"_dmarc.{zone}",
            dmarc,
            // p=none is the honest starting point: it asks for reports without
            // telling anyone to reject anything. A policy of reject published before
            // SPF and DKIM are both verified does not fail loudly — it silently
            // destroys delivery of every message that was already working.
            "Asks receivers to report what they saw. Move to p=quarantine, then p=reject, "
            + "once the reports show SPF and DKIM passing."));

        return records;
    }

    /// <summary>
    /// The SPF record. <c>~all</c> rather than <c>-all</c>: a soft fail is what a
    /// domain that has not yet checked its own reports should publish, because a
    /// hard fail on an incomplete record bounces real mail.
    /// </summary>
    private static string Spf(string? relayInclude, string mailHost)
    {
        var include = (relayInclude ?? string.Empty).Trim().TrimEnd('.');
        if (include.Length > 0)
        {
            return $"v=spf1 include:{include} ~all";
        }

        return mailHost.Length > 0 ? "v=spf1 mx ~all" : "v=spf1 ~all";
    }

    private static string NormalizeDomain(string domain)
    {
        var value = (domain ?? string.Empty).Trim().TrimEnd('.').ToLowerInvariant();
        if (value.Length == 0
            || value.Length > 253
            || value.StartsWith('-')
            || value.StartsWith('.')
            || value.EndsWith('-')
            || value.Contains("..", StringComparison.Ordinal)
            || !value.Contains('.', StringComparison.Ordinal)
            || !value.All(character => char.IsAsciiLetterOrDigit(character) || character is '.' or '-'))
        {
            throw new ArgumentException($"'{domain}' is not a domain.");
        }

        return value;
    }
}
