namespace PinqOps.Deploy;

/// <summary>
/// The environment file one colour's project is deployed with.
///
/// <para><b>Why a whole file rather than an override.</b> <c>--env-file</c> replaces
/// the project's <c>.env</c>; compose does not merge the two. Anything left out here
/// is not "inherited", it is gone — which for <c>PINQOPS_IMAGE</c> means the compose
/// default silently deploying somebody else's image. So this copies everything and
/// changes the one value that has to differ.</para>
/// </summary>
public static class ColorEnvironment
{
    /// <summary>The directory the colour files live in, beside the compose project.</summary>
    public const string DirectoryName = "colors";

    public static string DirectoryFor(string composeFilePath) =>
        Path.Combine(
            Path.GetDirectoryName(Path.GetFullPath(composeFilePath))
                ?? throw new ArgumentException("Compose file path has no parent directory.", nameof(composeFilePath)),
            DirectoryName);

    /// <summary>e.g. <c>/opt/pinqops/colors/green.env</c>.</summary>
    public static string FileFor(string composeFilePath, string color) =>
        Path.Combine(DirectoryFor(composeFilePath), $"{DeployColors.Normalize(color)}.env");

    /// <summary>
    /// Writes the file for one colour: every value from the project's <c>.env</c>,
    /// with the alias qualified by colour.
    ///
    /// <para>The alias is the only difference, and it is the one that makes the
    /// switch mean anything. Without it both colours would answer the same name and
    /// the proxy would split traffic between the version being tested and the one
    /// serving — there would be nothing left to switch.</para>
    /// </summary>
    public static string Write(string composeFilePath, string color, string alias)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(composeFilePath);
        ArgumentException.ThrowIfNullOrWhiteSpace(alias);

        var normalized = DeployColors.Normalize(color);
        var path = FileFor(composeFilePath, normalized);
        Directory.CreateDirectory(DirectoryFor(composeFilePath));

        // Written from scratch each time rather than edited in place: a value the
        // operator removed from .env has to disappear here too, and an accumulated
        // file would keep deploying it.
        var lines = new List<string>
        {
            "# Generated by pinqops — the environment for this project's " + normalized + " deploy.",
            "# Do not edit; it is rewritten from .env on every deploy.",
        };

        foreach (var (key, value) in EnvFileStore.GetAll(PinqOpsStatePaths.EnvFile(composeFilePath)))
        {
            if (key != Deployer.AliasVariable)
            {
                lines.Add($"{key}={value}");
            }
        }

        lines.Add($"{Deployer.AliasVariable}={DeployColors.Alias(alias, normalized)}");

        // Same protection the .env itself gets: these carry whatever secrets the
        // project's environment carries, because they are a copy of it.
        SecureFile.WriteAllText(path, string.Join('\n', lines) + '\n');
        return path;
    }
}
