using System.Text;

namespace PinqOps.Proxy;

/// <summary>What the generator refused to emit, and why.</summary>
public sealed record CaddyfileSkip(string What, string Reason)
{
    public override string ToString() => $"{What}: {Reason}";
}

/// <summary>A rendered Caddyfile and everything the generator left out of it.</summary>
public sealed record CaddyfileRender(string Caddyfile, IReadOnlyList<CaddyfileSkip> Skipped);

/// <summary>
/// Renders a Caddyfile from a <see cref="DomainConfig"/>. Pure and
/// deterministic (LF line endings) so it can be snapshot-tested and produced
/// identically by the dashboard and the runner CLI. Caddy handles Let's Encrypt
/// automatically; the only global settings are the ACME e-mail, an optional
/// staging CA for testing, and the shutdown grace period.
///
/// <para><b>This is the last boundary before Caddy executes the file.</b>
/// <c>domains.json</c> is written by both the dashboard and the runner CLI and is
/// loaded without validation, so every value emitted here is re-checked, and
/// anything that fails is skipped rather than written out. An entry whose domain or
/// container name carries whitespace, braces or newlines would otherwise inject
/// arbitrary directives — a second upstream, an extra site block.</para>
///
/// <para><b>Skipping is not free, which is why it is now reported.</b> A skipped
/// domain costs one route; a skipped <em>port</em> entry costs an app its only way
/// of being reached. <see cref="GenerateWithDiagnostics"/> returns what was left
/// out so a caller can log it and the dashboard can say so, instead of the operator
/// discovering it as a connection refused.</para>
/// </summary>
public static class CaddyfileGenerator
{
    private const string Header = "# Generated by pinqops-ui — do not edit; changes are overwritten.\n";

    /// <summary>The ports the proxy reserves for itself; a port entry may not claim one.</summary>
    private static readonly int[] ReservedPorts = [80, 443];

    /// <summary>Caddy accepts a grace period in seconds; anything past this is refused as a typo.</summary>
    private const int MaximumGracePeriodSeconds = 600;

    /// <summary>
    /// The Caddyfile for this config. Unchanged in shape from the first version:
    /// callers that only need the file — including every existing snapshot test —
    /// keep using this.
    /// </summary>
    public static string Generate(DomainConfig config) => GenerateWithDiagnostics(config).Caddyfile;

    /// <summary>
    /// True when the file has no global block and no site blocks — only the
    /// generated header and/or comments. Caddy adapts that to <c>{}</c>, which
    /// tears down every listener and cancels in-flight ACME if it is reloaded.
    /// </summary>
    public static bool IsEffectivelyEmpty(string caddyfile)
    {
        ArgumentNullException.ThrowIfNull(caddyfile);

        foreach (var raw in caddyfile.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            return false;
        }

        return true;
    }

    public static CaddyfileRender GenerateWithDiagnostics(DomainConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);

        var skipped = new List<CaddyfileSkip>();
        var builder = new StringBuilder();
        builder.Append(Header);

        AppendGlobalBlock(builder, config, skipped);

        var dns = config.Dns;
        var staticCache = EdgeModeRenderer.StaticCache(config.Edge);
        // Emitted only when it is asked for, so an install that never turns this on
        // renders exactly the file it rendered before.
        var accessLog = config.AccessLog ? AccessLogBlock : null;
        foreach (var entry in config.Domains)
        {
            AppendDomain(builder, entry, dns, staticCache, accessLog, skipped);
        }

        var claimed = new HashSet<int>();
        foreach (var entry in config.Ports)
        {
            AppendPort(builder, entry, claimed, skipped);
        }

        return new CaddyfileRender(builder.ToString(), skipped);
    }

    private static void AppendGlobalBlock(StringBuilder builder, DomainConfig config, List<CaddyfileSkip> skipped)
    {
        var global = new List<string>();

        if (!string.IsNullOrWhiteSpace(config.AcmeEmail))
        {
            if (IsSafeGlobalValue(config.AcmeEmail))
            {
                global.Add($"email {config.AcmeEmail.Trim()}");
            }
            else
            {
                skipped.Add(new CaddyfileSkip("ACME e-mail", "it contains whitespace, braces or control characters"));
            }
        }

        if (config.UseStagingCa)
        {
            global.Add("acme_ca https://acme-staging-v02.api.letsencrypt.org/directory");
        }

        if (config.GracePeriodSeconds > 0)
        {
            // Clamped rather than skipped: a grace period is a safety setting, and
            // dropping it because someone typed too many zeroes would quietly go
            // back to cutting live requests on every proxy restart.
            var seconds = Math.Min(config.GracePeriodSeconds, MaximumGracePeriodSeconds);
            global.Add($"grace_period {seconds}s");
        }

        // Behind a CDN every request arrives from the CDN. Naming the networks whose
        // forwarded headers are believed is what makes a rate limit bucket the
        // visitor rather than the whole internet, and what makes a country header
        // something other than a value anyone could have written.
        global.AddRange(EdgeModeRenderer.ServersBlock(EdgeModeRenderer.TrustedRanges(config.Edge, skipped)));

        if (global.Count == 0)
        {
            return;
        }

        builder.Append("{\n");
        foreach (var line in global)
        {
            builder.Append("    ").Append(line).Append('\n');
        }

        builder.Append("}\n");
    }

    private static void AppendDomain(
        StringBuilder builder,
        DomainEntry entry,
        DnsChallenge? dns,
        IReadOnlyList<string> staticCache,
        IReadOnlyList<string>? accessLog,
        List<CaddyfileSkip> skipped)
    {
        if (!entry.Enabled)
        {
            return;
        }

        if (entry.ProxyDeferred)
        {
            var deferredLabel = string.IsNullOrWhiteSpace(entry.Domain) ? "(unnamed domain)" : entry.Domain;
            skipped.Add(new CaddyfileSkip(
                deferredLabel,
                "HTTPS provision has not released it to the proxy yet (DNS wait)"));
            return;
        }

        var label = string.IsNullOrWhiteSpace(entry.Domain) ? "(unnamed domain)" : entry.Domain;
        var dnsUsable = dns?.IsUsable() ?? false;

        string domain;
        try
        {
            domain = DomainName.Normalize(entry.Domain, allowWildcard: dnsUsable);
        }
        catch (ArgumentException exception)
        {
            skipped.Add(new CaddyfileSkip(label, exception.Message));
            return;
        }

        if (!TryUpstream(entry.TargetContainer, entry.TargetPort, out var upstream, out var reason))
        {
            skipped.Add(new CaddyfileSkip(label, reason));
            return;
        }

        AppendSite(
            builder,
            domain,
            UpstreamRenderer.Render(entry.Upstream, upstream, entry.TargetPort, label, skipped),
            SecurityHeaderRenderer.Render(entry.Security, label, skipped),
            RateLimitRenderer.Render(entry.RateLimit, domain, label, skipped),
            staticCache,
            accessLog,
            TlsLinesFor(entry, domain, dns, skipped));
    }

    /// <summary>
    /// Custom files, DNS-01 for a wildcard, or nothing (automatic HTTP-01 ACME).
    /// </summary>
    private static IReadOnlyList<string>? TlsLinesFor(
        DomainEntry entry, string domain, DnsChallenge? dns, List<CaddyfileSkip> skipped)
    {
        if (DomainTlsModes.IsCustom(entry.TlsMode))
        {
            var folder = DomainCertificatePaths.FolderName(domain);
            if (folder is null)
            {
                skipped.Add(new CaddyfileSkip(domain, "its name is not safe for a certificate directory"));
                return null;
            }

            // Single-line tls with absolute paths inside the container. The proxy
            // directory is mounted at LogDirectory, so certs/ on the host is here.
            var cert = $"{ProxyPaths.CertsDirectoryInContainer}/{folder}/fullchain.pem";
            var key = $"{ProxyPaths.CertsDirectoryInContainer}/{folder}/privkey.pem";
            return [$"tls {cert} {key}"];
        }

        // Only a wildcard is switched to DNS-01. An ordinary domain keeps proving
        // itself over HTTP-01, which needs no credential and no zone access —
        // moving every domain onto the DNS challenge would make one wrong token
        // break certificates that were working.
        return DnsUsable(dns) && DomainName.IsWildcard(domain) ? TlsBlock(dns!) : null;
    }

    /// <summary>
    /// The <c>tls</c> block for a DNS-01 challenge. The token is referenced through
    /// the proxy container's environment rather than written here: the Caddyfile is
    /// regenerated constantly and sits beside a config two processes write, which is
    /// not where a credential that can edit an entire DNS zone belongs.
    /// </summary>
    /// <summary>
    /// The access log, as JSON to a file the dashboard reads.
    ///
    /// <para>Rolled by Caddy itself rather than left to grow: the summary only ever
    /// reads the most recent window, and an unbounded log on the proxy would be the
    /// one file nothing prunes.</para>
    /// </summary>
    private static readonly string[] AccessLogBlock =
    [
        "log {",
        $"    output file {ProxyPaths.AccessLogPath} {{",
        "        roll_size 32MiB",
        "        roll_keep 3",
        "    }",
        "    format json",
        "}",
    ];

    private static IReadOnlyList<string> TlsBlock(DnsChallenge dns) =>
    [
        "tls {",
        $"    dns {dns.Provider} {{env.{DnsProviders.TokenVariable}}}",
        "}",
    ];

    private static bool DnsUsable(DnsChallenge? dns) => dns?.IsUsable() ?? false;

    private static void AppendPort(
        StringBuilder builder, PortEntry entry, HashSet<int> claimed, List<CaddyfileSkip> skipped)
    {
        if (!entry.Enabled)
        {
            return;
        }

        var label = $"port {entry.HostPort}";

        if (!HostPort.IsValid(entry.HostPort))
        {
            skipped.Add(new CaddyfileSkip(label, "it is not a valid port (1-65535)"));
            return;
        }

        if (Array.IndexOf(ReservedPorts, entry.HostPort) >= 0)
        {
            skipped.Add(new CaddyfileSkip(label, "ports 80 and 443 belong to the proxy's own HTTP and HTTPS listeners"));
            return;
        }

        // Two site blocks with the same address make Caddy refuse the whole file,
        // which would take every other route down with it. Keeping the first is
        // arbitrary but deterministic, and the report says one was dropped.
        if (!claimed.Add(entry.HostPort))
        {
            skipped.Add(new CaddyfileSkip(label, "another entry already publishes this port"));
            return;
        }

        if (!TryUpstream(entry.TargetContainer, entry.TargetPort, out var upstream, out var reason))
        {
            skipped.Add(new CaddyfileSkip(label, reason));
            return;
        }

        // A bare ":port" address gets no automatic HTTPS, which is the point: an app
        // that used to publish 8080 itself must keep answering plain HTTP there.
        AppendSite(
            builder,
            $":{entry.HostPort}",
            UpstreamRenderer.Render(entry.Upstream, upstream, entry.TargetPort, label, skipped));
    }

    /// <summary>
    /// One site block. The <c>reverse_proxy</c> line is rendered through here so
    /// that when upstreams grow sub-directives — a load-balancing policy, a health
    /// check — there is one place that decides between the one-line and the block
    /// form, rather than each caller inventing its own.
    /// </summary>
    private static void AppendSite(
        StringBuilder builder,
        string address,
        UpstreamRender upstream,
        IReadOnlyList<string>? headers = null,
        IReadOnlyList<string>? rateLimit = null,
        IReadOnlyList<string>? staticCache = null,
        IReadOnlyList<string>? accessLog = null,
        IReadOnlyList<string>? tls = null)
    {
        builder.Append('\n').Append(address).Append(" {\n");

        foreach (var line in tls ?? [])
        {
            builder.Append("    ").Append(line).Append('\n');
        }

        // Beside the tls block rather than among the handlers: it configures the site
        // instead of handling a request. Nothing else tells Caddy to write the file,
        // so leaving it out is not a missing detail — it is a proxy that logs nothing
        // while the dashboard says the log is on.
        foreach (var line in accessLog ?? [])
        {
            builder.Append("    ").Append(line).Append('\n');
        }

        foreach (var line in staticCache ?? [])
        {
            builder.Append("    ").Append(line).Append('\n');
        }

        // Before the proxy line, so a refused request is refused without the
        // upstream ever hearing about it — which is the point of a ceiling.
        foreach (var line in rateLimit ?? [])
        {
            builder.Append("    ").Append(line).Append('\n');
        }

        if (headers is { Count: > 0 })
        {
            builder.Append("    header {\n");
            foreach (var line in headers)
            {
                builder.Append("        ").Append(line).Append('\n');
            }

            builder.Append("    }\n");
        }

        // Block form only when there is something to put in it, so a route with the
        // defaults renders as the single line it always did. The address is omitted
        // when a `dynamic` block supplies the upstreams instead: Caddy refuses a
        // reverse_proxy that has both.
        if (upstream.Directives.Count > 0)
        {
            builder.Append("    reverse_proxy");
            if (upstream.Address is { Length: > 0 })
            {
                builder.Append(' ').Append(upstream.Address);
            }

            builder.Append(" {\n");
            foreach (var line in upstream.Directives)
            {
                builder.Append("        ").Append(line).Append('\n');
            }

            builder.Append("    }\n");
        }
        else
        {
            builder.Append("    reverse_proxy ").Append(upstream.Address).Append('\n');
        }

        builder.Append("}\n");
    }

    /// <summary>
    /// The <c>container:port</c> an entry forwards to, or the reason it cannot.
    /// Both entry kinds validate identically — the target is the same shape — so
    /// the check lives once.
    /// </summary>
    private static bool TryUpstream(string? container, int port, out string upstream, out string reason)
    {
        upstream = string.Empty;

        if (string.IsNullOrWhiteSpace(container))
        {
            reason = "it names no container to forward to";
            return false;
        }

        if (!IsValidContainerName(container))
        {
            reason = $"'{container}' is not a container name pinqops will emit";
            return false;
        }

        if (!HostPort.IsValid(port))
        {
            reason = "it names no container port to forward to";
            return false;
        }

        upstream = $"{container}:{port}";
        reason = string.Empty;
        return true;
    }

    /// <summary>
    /// A name docker resolves and this file may carry: a container, or a network
    /// alias several replicas share. Starts alphanumeric, then only
    /// <c>[a-zA-Z0-9_.-]</c>. Rejects whitespace and anything that could break out
    /// of the <c>reverse_proxy</c> line into a second upstream or directive.
    ///
    /// <para>Public because the balancing renderer emits an alias into the same
    /// line, under the same rule — two copies of this predicate would eventually
    /// disagree, and the looser one would be the hole.</para>
    /// </summary>
    public static bool IsEmittableName(string? name) =>
        name is { Length: > 0 }
        && char.IsAsciiLetterOrDigit(name[0])
        && name.All(c => char.IsAsciiLetterOrDigit(c) || c is '_' or '.' or '-');

    private static bool IsValidContainerName(string name) => IsEmittableName(name);

    /// <summary>Guards a value emitted into the global block (the ACME e-mail):
    /// no whitespace, braces or control characters that could open or close a
    /// block.</summary>
    private static bool IsSafeGlobalValue(string value)
    {
        var trimmed = value.Trim();
        return trimmed.Length > 0
            && trimmed.All(c => !char.IsWhiteSpace(c) && !char.IsControl(c) && c is not ('{' or '}'));
    }
}
