namespace PinqOps.Proxy;

/// <summary>Whether a candidate Caddyfile is one Caddy will accept, and what it said if not.</summary>
public sealed record CaddyfileValidation(bool Valid, string? Error)
{
    public static readonly CaddyfileValidation Ok = new(true, null);
}

/// <summary>
/// Checks a Caddyfile before it replaces the live one, and keeps the last file the
/// proxy actually accepted so a bad one can be rolled back.
///
/// <para><b>Why this is not optional.</b> The proxy container runs with
/// <c>--restart unless-stopped</c>. A Caddyfile it cannot parse is therefore not
/// one failed reload — it is a container that crashes, restarts, crashes again, and
/// takes every domain and every published port down with it until someone edits a
/// file on the server by hand. The dashboard itself stays reachable on its own
/// port, which is the only reason that is recoverable at all.</para>
///
/// <para><b>Why a throwaway container.</b> The proxy mounts the Caddyfile as a
/// single read-only file, not its directory, so a candidate written beside it is
/// not visible from inside. <c>docker run --rm</c> with the directory mounted
/// validates with the same binary the proxy runs, works whether or not the proxy is
/// up, and cannot disturb the running one.</para>
///
/// <para>When docker itself cannot be reached the candidate is treated as
/// <em>valid</em>. That is deliberate: the alternative is that a docker outage
/// freezes domain management entirely, and a config that was generated by
/// <see cref="CaddyfileGenerator"/> — which re-validates every value it emits — is
/// already unlikely to be malformed. The validator is a second net, not the first.</para>
/// </summary>
public sealed class CaddyfileValidator
{
    private const string DockerExecutable = "docker";

    /// <summary>Where the proxy directory is mounted inside the validating container.</summary>
    private const string MountPath = "/pinqops-proxy";

    private static readonly TimeSpan ValidateTimeout = TimeSpan.FromSeconds(30);

    private readonly IProcessRunner _runner;
    private readonly string _proxyDirectory;
    private readonly string _image;

    public CaddyfileValidator(IProcessRunner runner, string proxyDirectory, string image)
    {
        ArgumentNullException.ThrowIfNull(runner);
        ArgumentException.ThrowIfNullOrWhiteSpace(proxyDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(image);
        _runner = runner;
        _proxyDirectory = proxyDirectory;
        _image = image;
    }

    /// <summary>
    /// Writes <paramref name="caddyfile"/> to the candidate path, asks Caddy whether
    /// it parses, and removes the candidate either way. The live file is never
    /// touched here — the caller installs it only on a valid result.
    /// </summary>
    public async Task<CaddyfileValidation> Validate(string caddyfile, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(caddyfile);

        Directory.CreateDirectory(_proxyDirectory);
        // A path of its own: two applies overlap often enough that sharing one
        // meant a validation could check a file another had written.
        var candidate = ProxyPaths.NewCandidatePath(_proxyDirectory);
        await File.WriteAllTextAsync(candidate, caddyfile, cancellationToken).ConfigureAwait(false);

        try
        {
            using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            timeout.CancelAfter(ValidateTimeout);

            var result = await _runner.RunAsync(
                DockerExecutable,
                [
                    "run", "--rm",
                    // No network and a read-only mount: validating a file must not be
                    // able to reach anything or change anything.
                    "--network", "none",
                    "-v", $"{_proxyDirectory}:{MountPath}:ro",
                    _image,
                    "caddy", "validate",
                    "--adapter", "caddyfile",
                    "--config", $"{MountPath}/{Path.GetFileName(candidate)}",
                ],
                workingDirectory: null,
                timeout.Token).ConfigureAwait(false);

            if (result.ExitCode == 0)
            {
                return CaddyfileValidation.Ok;
            }

            var message = result.StandardError.Length > 0 ? result.StandardError : result.StandardOutput;
            return LooksLikeDockerIsUnavailable(message)
                ? CaddyfileValidation.Ok
                : new CaddyfileValidation(false, Summarize(message));
        }
        catch (Exception exception) when (exception is OperationCanceledException && !cancellationToken.IsCancellationRequested)
        {
            // The validating container hung or the image could not be pulled in
            // time. Same reasoning as an unreachable docker: do not let it become a
            // lock on domain management.
            return CaddyfileValidation.Ok;
        }
        finally
        {
            TryDelete(candidate);
        }
    }

    /// <summary>Records the file the proxy has just accepted, so it can be restored.</summary>
    public void RememberGood(string caddyfile)
    {
        ArgumentNullException.ThrowIfNull(caddyfile);

        try
        {
            Directory.CreateDirectory(_proxyDirectory);
            SecureFile.WriteAllText(ProxyPaths.LastGoodPath(_proxyDirectory), caddyfile, ownerOnly: false);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            // Losing the rollback copy must not fail the change that succeeded.
        }
    }

    /// <summary>
    /// The last Caddyfile the proxy accepted, or null when there is none yet or
    /// the copy cannot be read.
    /// </summary>
    public string? TryReadLastGood()
    {
        var lastGood = ProxyPaths.LastGoodPath(_proxyDirectory);
        if (!File.Exists(lastGood))
        {
            return null;
        }

        try
        {
            return File.ReadAllText(lastGood);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return null;
        }
    }

    /// <summary>
    /// Puts the last accepted Caddyfile back in place. Returns false when there is
    /// none to restore — a first-ever apply that fails leaves nothing to fall back
    /// to, and saying so is more useful than silently doing nothing.
    /// </summary>
    public bool RestoreLastGood()
    {
        var lastGood = ProxyPaths.LastGoodPath(_proxyDirectory);
        if (!File.Exists(lastGood))
        {
            return false;
        }

        try
        {
            // Same inode-preserving write as Apply: File.Copy-replace can still
            // swap the inode on some platforms, and the live Caddyfile is a
            // single-file Docker bind mount.
            SecureFile.WriteAllTextPreservingInode(
                ProxyPaths.CaddyfilePath(_proxyDirectory),
                File.ReadAllText(lastGood),
                ownerOnly: false);
            return true;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    /// <summary>
    /// Whether the failure is docker's rather than the Caddyfile's. Matched on the
    /// daemon's own wording, the same strings <c>DockerDaemonError</c> classifies —
    /// treating "cannot connect to the Docker daemon" as a syntax error would
    /// report a broken config that is in fact fine.
    /// </summary>
    private static bool LooksLikeDockerIsUnavailable(string message)
    {
        string[] markers =
        [
            "cannot connect to the docker daemon",
            "is the docker daemon running",
            "permission denied while trying to connect",
            "docker: not found",
            "executable file not found",
        ];

        return Array.Exists(markers, marker => message.Contains(marker, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// The first few lines of Caddy's complaint. The full output repeats the whole
    /// adapted config, which is not something to put in a toast.
    /// </summary>
    private static string Summarize(string message)
    {
        var lines = message
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Take(3);
        var summary = string.Join(" ", lines).Trim();
        return summary.Length > 0 ? summary : "Caddy rejected the generated configuration.";
    }

    private static void TryDelete(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
        }
    }
}
